### PR TITLE
Adding sudo to execute pvesh CLI in openssh backend

### PR DESCRIPTION
**Pull request by TieWei**
Allow user to use sudo to execute pvesh commands

### CODE REVIEW

**Comment by swayf** [comment]
Thank you for the PR. :+1:

**Comment by rvbaz** [comment]
@swayf Thanks for merging this!  Any chance we can get a release out on PyPI with this fix?

**Comment by srsakhamuri** [comment]
Please also include PR #18 when releasing a new package.

**Comment by swayf** [comment]
I have published it right now... and PR #18 also :). Thanks for contributions

**Comment by rvbaz** [comment]
@swayf Thank you so much!

**Pull request merged**
